#yay config

#Minimum walk/fly someone can set with the walk/fly speed commands, cannot be less than -10
min-flyspeed: -10
min-walkspeed: -10
#Max speed someone can set with the walk/fly speed commands, cannot be greater than 10
max-flyspeed: 10
max-walkspeed: 10
#Should chatting take someone out of AFK? (Purpur-specific feature)
chatting-disables-afk: true
#Should /hat avoid swapping off items with binding?
hat-respects-binding-enchant: true
#Materials that should not be allowed to be used in /hat
hat-blocked-materials:
  - AIR
  - SPAWNER
  - COMMAND_BLOCK
  - STRUCTURE_VOID
#Should this list act like a whitelist instead of a blacklist
list-is-whitelist: false
#Max characters allowed in /rename (not including minimessage tags)
rename-max-characters: 50
#Items that cannot be trashed
trash-blacklist:
  - DIAMOND
  - DIAMOND_BLOCK
  - DIAMOND_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - DIAMOND_PICKAXE
  - DIAMOND_HOE
  - DIAMOND_SHOVEL
  - DIAMOND_AXE
  - DIAMOND_SWORD
  - NETHERITE_INGOT
  - ANCIENT_DEBRIS
  - NETHERITE_SCRAP
  - NETHERITE_HELMET
  - NETHERITE_CHESTPLATE
  - NETHERITE_LEGGINGS
  - NETHERITE_BOOTS
  - NETHERITE_PICKAXE
  - NETHERITE_HOE
  - NETHERITE_SHOVEL
  - NETHERITE_AXE
  - NETHERITE_SWORD
  - NETHERITE_BLOCK
  - BEACON
  - NETHER_STAR
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - PINK_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - LIME_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - RED_SHULKER_BOX
#Sounds for crafting inventories, if you would like no sound, please write "none"
craft-open-sound: BLOCK_BAMBOO_WOOD_BREAK
anvil-open-sound: BLOCK_ANVIL_USE
cartography-open-sound: UI_CARTOGRAPHY_TABLE_TAKE_RESULT
stonecutter-open-sound: UI_STONECUTTER_TAKE_RESULT
smithing-open-sound: BLOCK_SMITHING_TABLE_USE
grindstone-open-sound: BLOCK_GRINDSTONE_USE
loom-open-sound: ENTITY_VILLAGER_WORK_SHEPHERD
enderchest-open-sound: BLOCK_ENDER_CHEST_OPEN
trash-open-sound: BLOCK_BARREL_OPEN
trash-alert: BLOCK_NOTE_BLOCK_PLING

